from django.urls import include, path

from apps.accounts.views import (
    admin_dashboard,
    admin_groups_all,
    admin_groups_detail,
    admin_groups_running,
    admin_groups_closed,
    admin_groups_new,
    admin_bundles_pending,
    admin_bundles_all,
    admin_bundles_refunded,
    admin_bundles_lost,
    admin_bundles_won,
    admin_users_active,
    admin_users_all,
    admin_users_banned,
    admin_users_deactivated,
    admin_users_notifications,
    admin_users_verified,
    admin_users_unverified,
    admin_tickets_closed,
    admin_tickets_all,
    admin_tickets_answered,
    admin_tickets_pending,
    admin_deposits_rejected,
    admin_deposits_all,
    admin_deposits_approved,
    admin_deposits_pending,
    admin_withdrawals_rejected,
    admin_withdrawals_all,
    admin_withdrawals_approved,
    admin_withdrawals_pending,
)

app_name = "administrator"

urlpatterns = [
    path("dashboard/", admin_dashboard, name="dashboard"),
    path(
        "deposits/",
        include(
            [
                path(
                    "rejected/",
                    admin_deposits_rejected,
                    name="deposits_rejected",
                ),
                path(
                    "approved/",
                    admin_deposits_approved,
                    name="deposits_approved",
                ),
                path(
                    "pending/",
                    admin_deposits_pending,
                    name="deposits_pending",
                ),
                path(
                    "",
                    admin_deposits_all,
                    name="deposits_all",
                ),
            ]
        ),
    ),
    path(
        "withdrawals/",
        include(
            [
                path(
                    "rejected/",
                    admin_withdrawals_rejected,
                    name="withdrawals_rejected",
                ),
                path(
                    "approved/",
                    admin_withdrawals_approved,
                    name="withdrawals_approved",
                ),
                path(
                    "pending/",
                    admin_withdrawals_pending,
                    name="withdrawals_pending",
                ),
                path(
                    "",
                    admin_withdrawals_all,
                    name="withdrawals_all",
                ),
            ]
        ),
    ),
    path(
        "tickets/",
        include(
            [
                path(
                    "closed/",
                    admin_tickets_closed,
                    name="tickets_closed",
                ),
                path(
                    "answered/",
                    admin_tickets_answered,
                    name="tickets_answered",
                ),
                path(
                    "pending/",
                    admin_tickets_pending,
                    name="tickets_pending",
                ),
                path(
                    "",
                    admin_tickets_all,
                    name="tickets_all",
                ),
            ]
        ),
    ),
    path(
        "users/",
        include(
            [
                path(
                    "active/",
                    admin_users_active,
                    name="users_active",
                ),
                path(
                    "banned/",
                    admin_users_banned,
                    name="users_banned",
                ),
                path(
                    "unverified/",
                    admin_users_unverified,
                    name="users_unverified",
                ),
                path(
                    "verified/",
                    admin_users_verified,
                    name="users_verified",
                ),
                path(
                    "notifications/",
                    admin_users_notifications,
                    name="users_notifications",
                ),
                path(
                    "deactivated/",
                    admin_users_deactivated,
                    name="users_deactivated",
                ),
                path(
                    "",
                    admin_users_all,
                    name="users_all",
                ),
            ]
        ),
    ),
    path(
        "groups/",
        include(
            [
                path(
                    "running/",
                    admin_groups_running,
                    name="groups_running",
                ),
                path(
                    "closed/",
                    admin_groups_closed,
                    name="groups_closed",
                ),
                path(
                    "new/",
                    admin_groups_new,
                    name="groups_new",
                ),
                path(
                    "<str:slug>/",
                    admin_groups_detail,
                    name="groups_detail",
                ),
                path(
                    "",
                    admin_groups_all,
                    name="groups_all",
                ),
            ]
        ),
    ),
    path(
        "bundles/",
        include(
            [
                path(
                    "pending/",
                    admin_bundles_pending,
                    name="bundles_pending",
                ),
                path(
                    "refunded/",
                    admin_bundles_refunded,
                    name="bundles_refunded",
                ),
                path(
                    "lost/",
                    admin_bundles_lost,
                    name="bundles_lost",
                ),
                path(
                    "won/",
                    admin_bundles_won,
                    name="bundles_won",
                ),
                path(
                    "",
                    admin_bundles_all,
                    name="bundles_all",
                ),
            ]
        ),
    ),
]
