from django.urls import include, path

from apps.accounts.views import (
    admin_dashboard,
    admin_users_login_history,
    admin_wallet_deposit_history,
    admin_users_active,
    admin_users_all,
    admin_users_banned,
    admin_users_deactivated,
    admin_users_verified,
    admin_users_unverified,
    admin_users_detail,
    admin_users_assign_group,
    admin_unban_user,
    admin_suspend_user,
    admin_payouts_all,
    admin_payouts_approved,
    admin_payouts_cancelled,
    admin_withdrawals_all,
    admin_withdrawals_approved,
    admin_withdrawals_pending,
    admin_withdrawals_cancelled,
    admin_process_withdrawal,
)

app_name = "administrator"

urlpatterns = [
    path(
        "login-history/",
        admin_users_login_history,
        name="login_history",
    ),
    path(
        "transaction-history/",
        admin_wallet_deposit_history,
        name="transaction_history",
    ),
    path("dashboard/", admin_dashboard, name="dashboard"),
    # Withdrawals
    path(
        "withdrawals/",
        include(
            [
                path(
                    "approved/",
                    admin_withdrawals_approved,
                    name="withdrawals_approved",
                ),
                path(
                    "pending/",
                    admin_withdrawals_pending,
                    name="withdrawals_pending",
                ),
                path(
                    "cancelled/",
                    admin_withdrawals_cancelled,
                    name="withdrawals_cancelled",
                ),
                path(
                    "process/<uuid:withdrawal_id>/",
                    admin_process_withdrawal,
                    name="process_withdrawal",
                ),
                path(
                    "",
                    admin_withdrawals_all,
                    name="withdrawals_all",
                ),
            ]
        ),
    ),
    # Payouts
    path(
        "payouts/",
        include(
            [
                path(
                    "approved/",
                    admin_payouts_approved,
                    name="payouts_approved",
                ),
                path(
                    "cancelled/",
                    admin_payouts_cancelled,
                    name="payouts_cancelled",
                ),
                path(
                    "",
                    admin_payouts_all,
                    name="payouts_all",
                ),
            ]
        ),
    ),
    # Users
    path(
        "users/",
        include(
            [
                path(
                    "active/",
                    admin_users_active,
                    name="users_active",
                ),
                path(
                    "banned/",
                    admin_users_banned,
                    name="users_banned",
                ),
                path(
                    "unverified/",
                    admin_users_unverified,
                    name="users_unverified",
                ),
                path(
                    "verified/",
                    admin_users_verified,
                    name="users_verified",
                ),
                path(
                    "deactivated/",
                    admin_users_deactivated,
                    name="users_deactivated",
                ),
                path(
                    "<str:username>/suspend/",
                    admin_suspend_user,
                    name="suspend_user",
                ),
                path(
                    "<str:username>/unban/",
                    admin_unban_user,
                    name="unban_user",
                ),
                path(
                    "<str:username>/assigngroup/",
                    admin_users_assign_group,
                    name="assign_group",
                ),
                path(
                    "<str:username>/",
                    admin_users_detail,
                    name="users_detail",
                ),
                path(
                    "",
                    admin_users_all,
                    name="users_all",
                ),
            ]
        ),
    ),
]
