# Generated by Django 5.1.1 on 2024-10-05 10:13

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='Enter a unique name for the betting group.', max_length=255, unique=True, verbose_name='Group Name')),
                ('description', models.TextField(help_text='Provide a detailed description of the betting group.', verbose_name='Description')),
                ('status', models.CharField(choices=[('A', 'Running'), ('C', 'Closed')], db_index=True, default='A', help_text='Select a status for the betting group.', max_length=1, verbose_name='Status')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when the group was created.', verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when the group was last updated.', verbose_name='Updated At')),
            ],
            options={
                'verbose_name': 'Group',
                'verbose_name_plural': 'Groups',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status'], name='accounts_gr_status_d51285_idx'), models.Index(fields=['name'], name='accounts_gr_name_fde4c5_idx')],
            },
        ),
    ]
