# Generated by Django 5.1.1 on 2024-10-06 10:12

import django.core.validators
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bundle',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='Enter a unique name for the group bundle.', max_length=255, unique=True, verbose_name='Bundle Name')),
                ('price', models.DecimalField(decimal_places=2, help_text='Enter the price for one bundle.', max_digits=10, verbose_name='Bundle Price')),
                ('minimum_win_multiplier', models.PositiveSmallIntegerField(default=3, help_text='Minimum multiplier value to calculate minimum potential wins.', validators=[django.core.validators.MinValueValidator(1)], verbose_name='Minimum Win Multiplier')),
                ('maximum_win_multiplier', models.PositiveSmallIntegerField(default=5, help_text='Maximum multiplier value to calculate maximum potential wins.', validators=[django.core.validators.MinValueValidator(1)], verbose_name='Maximum Win Multiplier')),
                ('min_bundles_per_user', models.PositiveIntegerField(default=2, help_text='Minimum number of bundles a user can purchase.', validators=[django.core.validators.MinValueValidator(1)], verbose_name='Minimum Bundles per User')),
                ('max_bundles_per_user', models.PositiveIntegerField(default=10, help_text='Maximum number of bundles a user can purchase.', validators=[django.core.validators.MinValueValidator(1)], verbose_name='Maximum Bundles per User')),
                ('status', models.CharField(choices=[('P', 'Pending'), ('W', 'Won'), ('L', 'Lost'), ('R', 'Refunded')], default='P', help_text='Current status of the bundle.', max_length=1, verbose_name='Status')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when the bundle was created.', verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when the bundle was last updated.', verbose_name='Updated At')),
                ('group', models.OneToOneField(help_text='Select the group this bundle is associated with.', on_delete=django.db.models.deletion.CASCADE, related_name='bundles', to='accounts.group', verbose_name='Group')),
            ],
            options={
                'verbose_name': 'Bundle',
                'verbose_name_plural': 'Bundles',
                'ordering': ['-created_at'],
            },
        ),
    ]
