# Generated by Django 5.1.1 on 2024-12-05 18:50

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="deposit",
            name="bundle",
        ),
        migrations.RemoveField(
            model_name="payout",
            name="bundle",
        ),
        migrations.RemoveField(
            model_name="deposit",
            name="user",
        ),
        migrations.RemoveField(
            model_name="group",
            name="bettors",
        ),
        migrations.RemoveField(
            model_name="payout",
            name="user",
        ),
        migrations.DeleteModel(
            name="Bundle",
        ),
        migrations.DeleteModel(
            name="Deposit",
        ),
        migrations.DeleteModel(
            name="Group",
        ),
        migrations.DeleteModel(
            name="Payout",
        ),
    ]
