# Generated by Django 5.1.1 on 2024-10-06 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_bundle_group'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='description',
            field=models.TextField(help_text='Provide a detailed description of the betting group.', max_length=140, verbose_name='Description'),
        ),
    ]
