# Generated by Django 5.1.1 on 2024-10-07 01:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_group_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bundle',
            name='status',
            field=models.CharField(choices=[('P', 'Pending'), ('W', 'Won'), ('L', 'Lost')], default='P', help_text='Current status of the bundle.', max_length=1, verbose_name='Status'),
        ),
    ]
