# Generated by Django 5.1.1 on 2024-10-13 02:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_alter_deposit_quantity_action'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='phone_number',
            field=models.CharField(default='', max_length=11, verbose_name='phone number'),
            preserve_default=False,
        ),
    ]
