# Generated by Django 5.1.1 on 2024-10-14 01:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_action_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='about',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='location',
        ),
    ]
