# Generated by Django 5.1.1 on 2024-10-16 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_remove_profile_about_remove_profile_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='deposit',
            name='paystack_id',
            field=models.CharField(blank=True, max_length=150),
        ),
    ]
