# Generated by Django 5.1.1 on 2024-10-20 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0016_bundle_participants'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='status',
            field=models.CharField(choices=[('R', 'Running'), ('C', 'Closed')], db_index=True, default='R', help_text='Select a status for the betting group.', max_length=1, verbose_name='Status'),
        ),
    ]
