# Generated by Django 5.1.1 on 2024-10-22 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0017_alter_group_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deposit',
            name='reference',
        ),
        migrations.AlterField(
            model_name='deposit',
            name='paystack_id',
            field=models.CharField(blank=True, max_length=150, unique=True, verbose_name='Paystack Reference ID'),
        ),
    ]
