# Generated by Django 5.1.1 on 2024-10-28 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0020_profile_payout_information'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payout',
            name='transaction_id',
        ),
        migrations.AlterField(
            model_name='payout',
            name='note',
            field=models.TextField(help_text='A note by the admin.', verbose_name='Payout Note'),
        ),
    ]
