# Generated by Django 5.1.1 on 2024-10-29 17:23

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0021_remove_payout_transaction_id_alter_payout_note'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bundle',
            name='max_bundles_per_user',
            field=models.PositiveIntegerField(help_text='Maximum number of bundles a user can purchase.', validators=[django.core.validators.MinValueValidator(1)], verbose_name='Maximum Bundles per User'),
        ),
        migrations.AlterField(
            model_name='bundle',
            name='maximum_win_multiplier',
            field=models.PositiveSmallIntegerField(help_text='Maximum multiplier value to calculate maximum potential wins.', validators=[django.core.validators.MinValueValidator(1)], verbose_name='Maximum Win Multiplier'),
        ),
        migrations.AlterField(
            model_name='bundle',
            name='min_bundles_per_user',
            field=models.PositiveIntegerField(help_text='Minimum number of bundles a user can purchase.', validators=[django.core.validators.MinValueValidator(1)], verbose_name='Minimum Bundles per User'),
        ),
        migrations.AlterField(
            model_name='bundle',
            name='minimum_win_multiplier',
            field=models.PositiveSmallIntegerField(help_text='Minimum multiplier value to calculate minimum potential wins.', validators=[django.core.validators.MinValueValidator(1)], verbose_name='Minimum Win Multiplier'),
        ),
    ]
