# Generated by Django 5.1.1 on 2024-10-30 00:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0022_alter_bundle_max_bundles_per_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deposit',
            name='status',
            field=models.CharField(choices=[('P', 'Pending'), ('A', 'Approved'), ('C', 'Cancelled')], default='P', max_length=1, verbose_name='Status'),
        ),
    ]
