# Generated by Django 5.1.1 on 2024-10-30 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0025_loginhistory'),
    ]

    operations = [
        migrations.AddField(
            model_name='loginhistory',
            name='browser',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='loginhistory',
            name='device',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='loginhistory',
            name='os',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
