# Generated by Django 5.1.1 on 2024-10-30 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0026_loginhistory_browser_loginhistory_device_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='loginhistory',
            options={'ordering': ['-login_time']},
        ),
        migrations.AddField(
            model_name='loginhistory',
            name='location',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
