# Generated by Django 5.1.1 on 2024-10-30 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0027_alter_loginhistory_options_loginhistory_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='account_activated_at',
            field=models.DateTimeField(blank=True, help_text='The date when the user activated their account.', null=True, verbose_name='Account Activation Date'),
        ),
    ]
