# Generated by Django 5.1.1 on 2024-11-12 18:35

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0029_alter_action_target_id'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='bettors',
            field=models.ManyToManyField(blank=True, help_text='Users who are part of this group.', related_name='bet_groups', to=settings.AUTH_USER_MODEL, verbose_name='Bettors'),
        ),
    ]
