# Generated by Django 5.1.1 on 2024-11-27 22:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0030_group_bettors'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deposit',
            name='paystack_id',
        ),
    ]
