# Generated by Django 5.1.1 on 2024-12-01 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0031_remove_deposit_paystack_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='payout_information',
            field=models.TextField(blank=True, help_text='Bank account information for Withdrawals', verbose_name='Bank Account Information'),
        ),
    ]
