# Generated by Django 5.1.1 on 2024-12-02 02:49

import django.core.validators
import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Wallet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wallet_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('balance', models.DecimalField(decimal_places=2, default=0.0, help_text='Current wallet balance.', max_digits=12)),
                ('currency', models.CharField(default='NGN', max_length=50)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='wallet', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Deposit',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('paystack_id', models.CharField(blank=True, max_length=20, null=True, unique=True)),
                ('amount', models.DecimalField(decimal_places=2, help_text='Amount deposited.', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('100.00'))], verbose_name='Deposit Amount (₦)')),
                ('description', models.CharField(blank=True, max_length=255)),
                ('status', models.CharField(choices=[('P', 'Pending'), ('C', 'Completed'), ('F', 'Failed')], default='P', help_text='Status of the deposit transaction.', max_length=1)),
                ('gateway_response', models.CharField(blank=True, help_text='Response from the payment gateway.', max_length=255)),
                ('channel', models.CharField(blank=True, help_text="Payment channel used, e.g., 'card'.", max_length=50)),
                ('ip_address', models.GenericIPAddressField(blank=True, help_text='IP address of the customer at the time of transaction.', null=True)),
                ('paid_at', models.DateTimeField(blank=True, help_text='Timestamp when payment was completed.', null=True)),
                ('authorization_code', models.CharField(blank=True, help_text='Authorization code for the payment.', max_length=100)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wallet_deposits', to=settings.AUTH_USER_MODEL)),
                ('wallet', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='deposits', to='wallets.wallet')),
            ],
            options={
                'ordering': ['-paid_at', '-created'],
            },
        ),
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('transaction_type', models.CharField(help_text='Type of transaction (Deposit, Withdrawal, Purchase, Winning).', max_length=50)),
                ('transaction_id', models.CharField(help_text='Unique ID of the related transaction (Deposit, Purchase, etc.)', max_length=100, unique=True)),
                ('amount', models.DecimalField(decimal_places=2, help_text='Amount involved in the transaction.', max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('balance_before', models.DecimalField(decimal_places=2, help_text='Wallet balance before the transaction.', max_digits=12)),
                ('balance_after', models.DecimalField(decimal_places=2, help_text='Wallet balance after the transaction.', max_digits=12)),
                ('timestamp', models.DateTimeField(auto_now_add=True, help_text='Timestamp of the balance change.')),
                ('wallet', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='audit_logs', to='wallets.wallet')),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='Withdrawal',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('amount', models.DecimalField(decimal_places=2, help_text='Requested withdrawal amount.', max_digits=10)),
                ('description', models.TextField(help_text='Withdrawal description.', max_length=300, verbose_name='Description')),
                ('note', models.TextField(blank=True, help_text='Withdrawal note from Administrator.', null=True, verbose_name='Feedback Note')),
                ('status', models.CharField(choices=[('P', 'Pending'), ('A', 'Approved'), ('D', 'Declined'), ('C', 'Cancelled')], default='P', help_text='Status of the withdrawal request.', max_length=10)),
                ('processed_at', models.DateTimeField(blank=True, help_text='Date when the withdrawal was processed.', null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='withdrawals', to=settings.AUTH_USER_MODEL)),
                ('wallet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='withdrawals', to='wallets.wallet')),
            ],
            options={
                'ordering': ['-created'],
            },
        ),
    ]
