# Generated by Django 5.1.1 on 2024-11-14 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallets', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='deposit',
            options={'ordering': ['-paid_at', '-created']},
        ),
        migrations.AddField(
            model_name='wallet',
            name='currency',
            field=models.CharField(default='NGN', max_length=50),
        ),
        migrations.AlterField(
            model_name='deposit',
            name='transaction_id',
            field=models.CharField(help_text='Unique transaction ID from Paystack.', max_length=200, unique=True),
        ),
    ]
