# Generated by Django 5.1.1 on 2024-11-22 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallets', '0003_deposit_paystack_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deposit',
            name='transaction_id',
            field=models.CharField(blank=True, help_text='Unique transaction ID from Paystack.', max_length=200, null=True, unique=True),
        ),
    ]
