# Generated by Django 5.1.1 on 2024-11-25 06:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wallets', '0005_remove_deposit_transaction_id'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='auditlog',
            options={'ordering': ['-timestamp']},
        ),
    ]
