# Generated by Django 5.1.1 on 2024-11-29 21:16

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallets', '0006_alter_auditlog_options'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Withdrawal',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('amount', models.DecimalField(decimal_places=2, help_text='Requested withdrawal amount.', max_digits=10)),
                ('description', models.TextField(help_text='Withdrawal description.', max_length=300, verbose_name='Description')),
                ('note', models.TextField(blank=True, help_text='Withdrawal note from Administrator.', null=True, verbose_name='Feedback Note')),
                ('status', models.CharField(choices=[('P', 'Pending'), ('A', 'Approved'), ('D', 'Declined'), ('C', 'Cancelled')], default='P', help_text='Status of the withdrawal request.', max_length=10)),
                ('processed_at', models.DateTimeField(blank=True, help_text='Date when the withdrawal was processed.', null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='withdrawals', to=settings.AUTH_USER_MODEL)),
                ('wallet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='withdrawals', to='wallets.wallet')),
            ],
        ),
    ]
