# Generated by Django 5.1.1 on 2024-12-01 08:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wallets', '0007_withdrawal'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='withdrawal',
            options={'ordering': ['-created']},
        ),
    ]
